theme: jekyll-theme-minimal
title: John Cook
logo: /Images/118070659_10216635895945654_7500484329869396564_n%20(2).jpg
description: I am a Data Science student at Central Connecticut State University and work in finance. I love everything about data from gathering, to cleaning, exploring, and gaining important insights to provide real value.
