theme: jekyll-theme-minimal
title: [John Cook | Data Analyst]
logo: "https://github.com/johngncook/Analytics-Portfolio/blob/main/Images/118070659_10216635895945654_7500484329869396564_n%20(2).JPG"
description: [Analytics Portfolio]

